// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ArcAuthentication.Topology;
//
//    var cgiDevices = CgiDevices.FromJson(jsonString);

namespace ArcAuthentication.Topology
{
    using Newtonsoft.Json;

    public partial class CgiDevices
    {
        [JsonProperty("stations")]
        public Station[] Stations { get; set; }
    }

    public partial class CgiDevices
    {
        public static CgiDevices FromJson(string json) => JsonConvert.DeserializeObject<CgiDevices>(json, ArcAuthentication.Topology.Converter.Settings);
    }
}
